# Generated by Django 5.2.17 on 2026-09-21 13:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_OS', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('data_prevista', models.DateField()),
                ('descricao', models.TextField()),
                ('endereco', models.CharField(max_length=255)),
                ('numero_endereco', models.CharField(max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(choices=[('SINALIZAÇÃO HORIZONTAL', 'Sinalização horizontal'), ('SINALIZAÇÃO VERTICAL', 'Sinalização vertical'), ('SINALIZAÇÃO SEMAFÓRICA', 'Sinalização semafórica')], default='SINALIZAÇÃO HORIZONTAL', max_length=30)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM EXECUÇÃO', 'Em execução'), ('EM ANÁLISE', 'Em análise'), ('CONCLUÍDA', 'Concluída')], default='ABERTA', max_length=30)),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_atribuidas', to='usuarios.prestador')),
            ],
        ),
    ]
